// THIS FILE IS GENERATED BY src/core/gen/includes_files.cpp
// DON'T CHANGE IT!
#pragma once
#include "./cmd/calc.cpp"
#include "./cmd/exe.cpp"
#include "./cmd/cpp.cpp"
#include "./cmd/mv.cpp"
#include "./cmd/help.cpp"
#include "./cmd/cls.cpp"
#include "./cmd/ls.cpp"
#include "./cmd/exit.cpp"
#include "./cmd/rm.cpp"
#include "./cmd/mk.cpp"
#include "./cmd/say.cpp"
#include "./cmd/cd.cpp"
